services:
  server:
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "5000:5000"
  
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server
